server:
    port: ${APPLICATION_PORT:8080}
# spring configuration
spring:
    datasource:
        platform: postgres
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/${DATABASE_NAME:postgres}
        username: ${DATABASE_USERNAME:postgres}
        password: ${DATABASE_PASSWORD:root}
