version: "3.9"
volumes:
    pg_data: {}
networks:
    template-project: {}
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=root
        ports:
            - 5433:5432
        volumes:
            - pg_data:/var/lib/postgresql
        networks:
            - template-project
    backend:
        image: rgx69/template-project
        environment:
            - DATABASE_HOST=postgres
            - DATABASE_NAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=root
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - 8080:8080
        networks:
            - template-project
